# Generated by Django 4.2.16 on 2024-12-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_address_pvz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address_pvz',
            field=models.CharField(default='-', max_length=250),
        ),
    ]
