# Generated by Django 4.2.16 on 2025-10-27 11:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
        ('catalog', '0012_model_type_brand_model_type_description_and_more'),
        ('orders', '0003_alter_order_address_pvz'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='coupons.coupon'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='color',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='catalog.color'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='m_type',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='catalog.model_type'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.ForeignKey(default='4', on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='catalog.size'),
        ),
    ]
