# Generated by Django 4.2.16 on 2026-03-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_coupon_order_delivery_sum_order_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cdek_order_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID заказа в CDEK'),
        ),
        migrations.AddField(
            model_name='order',
            name='cdek_track_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Трек-номер CDEK'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Статус доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='last_status_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление статуса'),
        ),
    ]
