# Generated by Django 4.2.16 on 2026-03-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_cdek_order_id_order_cdek_track_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cdek_order_id',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='cdek_track_number',
            new_name='track_number',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Вид доставки'),
        ),
    ]
