# Generated by Django 4.2.16 on 2026-08-03 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_rename_cdek_order_id_order_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=79999999999, help_text='Введите номер в формате: +7XXXXXXXXXX', max_length=20, validators=[django.core.validators.RegexValidator(message='Телефон должен быть в формате +7XXXXXXXXXX (10 цифр после +7)', regex='^\\+7\\d{10}$')], verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
