# Generated by Django 4.2.16 on 2026-01-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Город')),
                ('region', models.CharField(max_length=100, verbose_name='Регион')),
                ('country', models.CharField(default='Россия', max_length=50, verbose_name='Страна')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярный')),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('detection_count', models.IntegerField(default=0, verbose_name='Количество определений')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ['-is_default', '-is_popular', 'order', 'name'],
                'indexes': [models.Index(fields=['name', 'region'], name='homepage_ci_name_0cfaba_idx'), models.Index(fields=['is_active', 'is_popular'], name='homepage_ci_is_acti_9da814_idx'), models.Index(fields=['detection_count'], name='homepage_ci_detecti_47dde8_idx')],
            },
        ),
    ]
