# Generated by Django 4.2.16 on 2026-01-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='name_ru',
            field=models.CharField(default='Город', max_length=100, verbose_name='Город_ру'),
            preserve_default=False,
        ),
    ]
