# Generated by Django 4.2.16 on 2026-04-13 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0021_gallery_type_product_type_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, help_text='Уникальный идентификатор пользователя в мессенджере MAX', max_length=100, verbose_name='ID пользователя в MAX')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('price_at_add', models.DecimalField(decimal_places=2, help_text='Цена товара в момент добавления в корзину', max_digits=10, verbose_name='Цена при добавлении')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.color', verbose_name='Цвет')),
                ('model_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.model_type', verbose_name='Модель')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Товар')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.size', verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Товар в корзине (бот)',
                'verbose_name_plural': 'Товары в корзине (бот)',
                'ordering': ('-created_at',),
                'unique_together': {('user_id', 'product', 'size', 'color', 'model_type')},
            },
        ),
    ]
