# Generated by Django 3.2.16 on 2024-10-02 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Назначение',
                'verbose_name_plural': 'Назначения',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Brend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Class_compress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Класс компрессии',
                'verbose_name_plural': 'Класс компрессии',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('color', models.CharField(max_length=7, unique=True, verbose_name='Цветовой HEX-код')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвет',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('code', models.CharField(max_length=128, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Male',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Пол',
                'verbose_name_plural': 'Пол',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Side',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Строна',
                'verbose_name_plural': 'Сторона',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Soсk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Носок',
                'verbose_name_plural': 'Носок',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Type_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Вид изделия',
                'verbose_name_plural': 'Вид изделия',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Wide_hips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Широкое бедро',
                'verbose_name_plural': 'Широкое бедро',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('Appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.appointment')),
                ('Class_compress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.class_compress')),
                ('Color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.color')),
                ('Male', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.male')),
                ('Side', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.side')),
                ('Sock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.soсk')),
                ('Type_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.type_product')),
                ('Wide_hips', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.wide_hips')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.brend')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='brend',
            name='country_brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.country'),
        ),
    ]
