# Generated by Django 3.2.16 on 2024-10-02 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20241002_1711'),
    ]

    operations = [
        #migrations.AlterField(
        #    model_name='product',
        #    name='Model_type',
        #    field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='catalog.model_type'),
        #),
    ]
