# Generated by Django 3.2.16 on 2024-10-02 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20241002_1729'),
        ('catalog', '0003_alter_product_model_type'),
    ]

    operations = [
    ]
