# Generated by Django 4.2.16 on 2024-10-11 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_merge_20241002_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Model_type',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='catalog.model_type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Size',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='catalog.size'),
        ),
    ]
