# Generated by Django 4.2.16 on 2024-10-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_image_alter_product_model_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='1', max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
