# Generated by Django 4.2.16 on 2025-10-24 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_product_articul_product_code'),
    ]

    operations = [
    ]
