# Generated by Django 4.2.16 on 2025-10-27 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_model_type_brand_model_type_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_type',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.brend', verbose_name='Бренд'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model_type',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='articul',
            field=models.CharField(default='P280', max_length=16, verbose_name='Артикул'),
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(default='51723', max_length=16, verbose_name='Код товара'),
        ),
        migrations.AddField(
            model_name='size',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.brend', verbose_name='Бренд'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='Model_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.model_type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.size'),
        ),
    ]
