# Generated by Django 4.2.16 on 2025-10-31 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_model_type_brand_model_type_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Color',
        ),
        migrations.AddField(
            model_name='product',
            name='Color',
            field=models.ManyToManyField(to='catalog.color', verbose_name='Цвета'),
        ),
    ]
