# Generated by Django 4.2.16 on 2025-11-11 18:43

import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_product_seo_alt_product_seo_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ankle_circumference', django.contrib.postgres.fields.ranges.IntegerRangeField(verbose_name='Обхват щиколотки (см)')),
                ('calf_circumference', django.contrib.postgres.fields.ranges.IntegerRangeField(verbose_name='Обхват икры (см)')),
                ('circumference_under_knee', django.contrib.postgres.fields.ranges.IntegerRangeField(verbose_name='Обхват под коленом (см)')),
                ('mid_thigh_circumference', django.contrib.postgres.fields.ranges.IntegerRangeField(verbose_name='Обхват середины бедра (см)')),
                ('Upper_thigh_circumference', django.contrib.postgres.fields.ranges.IntegerRangeField(verbose_name='Обхват бедра верхний (см)')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.size', verbose_name='Детали размера')),
            ],
            options={
                'verbose_name': 'Детали размера',
                'verbose_name_plural': 'Детали размеров',
            },
        ),
    ]
