# Generated by Django 4.2.16 on 2025-11-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_sizedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='brend',
            name='size_table_image',
            field=models.ImageField(blank=True, help_text='Загрузите изображение с таблицей размеров для этого бренда', null=True, upload_to='brands/size_tables/', verbose_name='Изображение таблицы размеров'),
        ),
    ]
