# Generated by Django 4.2.16 on 2025-12-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_brend_size_table_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AddField(
            model_name='product',
            name='seo_h1',
            field=models.CharField(blank=True, max_length=255, verbose_name='H1 заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_keywords',
            field=models.TextField(blank=True, verbose_name='Ключевые слова'),
        ),
    ]
