# Generated by Django 4.2.16 on 2025-12-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_alter_product_options_product_seo_h1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.PositiveIntegerField(unique=True, verbose_name='Код товара'),
        ),
    ]
