# Generated by Django 4.2.16 on 2025-12-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_alter_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Код товара'),
        ),
    ]
