# Generated by Django 4.2.16 on 2026-02-11 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_product_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='type_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='type_images', to='catalog.type_product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='type_product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
